# The URL the site will be built for
base_url = "https://courses.hilgers.dev"
title = "University Courses"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
katex_enable = true
katex_auto_render = true
